name: Promote and Deploy PROD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  promote-and-deploy:
    name: Promote MAIN to PROD

    runs-on: ubuntu-latest

    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Promote MAIN to PROD
        run: |
          git fetch origin

          git checkout prod
          git pull origin prod

          git merge origin/main --no-edit

          git push origin prod

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate PROD bundle
        run: databricks bundle validate -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy DAB to PROD
        run: databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Run PROD notebook
        run: databricks bundle run -t prod demo_notebook_job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}