name: Deploy DEV

on:
  push:
    branches:
      - dev

  workflow_dispatch:

permissions:
  contents: read

jobs:

  deploy-dev:

    name: Deploy to DEV

    runs-on: ubuntu-latest

    environment: dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI
        run: databricks --version

      - name: Validate DAB
        run: databricks bundle validate -t dev

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy DAB to DEV
        run: databricks bundle deploy -t dev

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Run DEV notebook
        run: databricks bundle run -t dev demo_notebook_job

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}